# JoinCommands by HuaYoyu Config File;
############################################################################
# {player} = the player that command will be executed towards;
# Command executed when player joins the game;
enablejoin: true
JoinCommand: 
- effect {player} 1 200 0
- effect {player} 16 99999 0
# Command executed when player dies;
enabledeath: false
DeathCommand: 
- say {player} has Died again...
# Command executed when player does /spawn or respawns into the game;
enablespawn: true
RespawnCommand: 
- effect {player} 1 200 0
- effect {player} 16 99999 0
# Command executed when player leaves the game;
enableleave: false
LeaveCommand: 
- say {player} leave the server!
